version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - deploy/.env.prod
    networks:
      - datalake_network
  minio:
    image: minio:latest
    container_name: minio_db
    networks:
      - datalake_network
    env_file:
      - deploy/.env.prod
  flask:
    build: .
    image: datalake_pawa:0.0.1
    container_name: dl
    env_file:
      - minio
      - mongo
    networks:
      - datalake_network
  nginx:
    build: ./deploy/nginx
    image: nginx-datalake:0.0.1
    container_name: naginx-datalake
    ports:
      - "8080:80"
    depends_on:
      - flask
    networks:
      - datalake_network
networks:
  datalake_network:




