version: '3'

services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo_db
    hostname: mongo_db
    ports:
      - "27017:27017"
    env_file:
      - deploy/.env.prod
    networks:
      - datalake_network
  minio:
    image: 'bitnami/minio:latest'
    #command: server /data --address '0.0.0.0:9000' --console-address '0.0.0.0:9001'
    container_name: minio_db
    hostname: minio_db
    ports:
      - "9001:9001"
      - "9000:9000"
    env_file:
      - deploy/.env.prod
    networks:
      - datalake_network
  flask:
    build: .
    image: datalake_pawa:0.0.1
    container_name: dl
    env_file:
      - deploy/.env.prod
    depends_on:
      - minio
      - mongo
    networks:
      - datalake_network
  nginx:
    build: ./deploy/nginx
    image: nginx-datalake:0.0.1
    container_name: nginx-datalake
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - datalake_network
networks:
  datalake_network:




